### ISSUE TITLE
Public getters of POJOs are not exposed to custom functions

### ISSUE THREAD

**Issue by ddavidyuk** [camunda/feel-scala#360] opened 2021-11-17 14:55 UTC
**Describe the bug**
When Java object is passed to a decision and then from the decision to a custom FEEL function, in the Java body of the function we get empty instance of camundajar.impl.scala.collection.convert.JavaCollectionWrappers$MapWrapper, not the original Java object (or even some kind of proxy map).

**To Reproduce**
The following code snipped can be used to reproduce the bug:
```java
public class DmnEngineTest2 {
    static final String DMN = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<definitions xmlns=\"https://www.omg.org/spec/DMN/20191111/MODEL/\" xmlns:dmndi=\"https://www.omg.org/spec/DMN/20191111/DMNDI/\" xmlns:dc=\"http://www.omg.org/spec/DMN/20180521/DC/\" id=\"Definitions_1yu2lcr\" name=\"DRD\" namespace=\"http://camunda.org/schema/1.0/dmn\" exporter=\"Camunda Modeler\" exporterVersion=\"4.11.1\">\n" +
            "  <decision id=\"pojo\" name=\"custom function with Java pojo (literal)\">\n" +
            "    <variable id=\"InformationItem_0zmcpc8\" name=\"result\" typeRef=\"string\" />\n" +
            "    <literalExpression id=\"LiteralExpression_1gccogk\" expressionLanguage=\"feel\">\n" +
            "      <text>custom_pojo(pojo_input)</text>\n" +
            "    </literalExpression>\n" +
            "  </decision>\n" +
            "</definitions>";

    public void run() {
        DefaultDmnEngineConfiguration dmnEngineConfig = (DefaultDmnEngineConfiguration) DmnEngineConfiguration.createDefaultDmnEngineConfiguration();
        dmnEngineConfig.feelCustomFunctionProviders(Collections.singletonList(new CustomFuncProvider()));

        DmnEngine dmnEngine = dmnEngineConfig.buildEngine();

        DmnModelInstance dmnModel = Dmn.readModelFromStream(new ByteArrayInputStream(DMN.getBytes(StandardCharsets.UTF_8)));

        DmnDecision decision = dmnEngine.parseDecision("pojo", dmnModel);

        Map<String, Object> variables = new HashMap<>();
        variables.put("pojo_input", new Pojo());
        dmnEngine.evaluateDecision(decision, variables);
    }

    public static class CustomFuncProvider implements FeelCustomFunctionProvider {
        private final Map<String, CustomFunction> functions = new HashMap<>();

        public CustomFuncProvider() {
            functions.put("custom_pojo", CustomFunction.create()
                    .setParams("val")
                    .setFunction(args -> {
                        System.out.println(args.get(0) + " class=" + args.get(0).getClass().getName());
                        Map map = (Map) args.get(0);
                        System.out.println("list=" + map.get("list") + " num=" + map.get("num"));
                        return map.get("num");
                    }).build());
        }

        @Override
        public Optional<CustomFunction> resolveFunction(String key) {
            return Optional.ofNullable(functions.get(key));
        }

        @Override
        public Collection<String> getFunctionNames() {
            return functions.keySet();
        }
    }

    public static class Pojo {
        private int num = 10;
        private List<Integer> list = Arrays.asList(1, 2, 3);

        public int getNum() {
            return num;
        }

        public List<Integer> getList() {
            return list;
        }
    }
}
```
When the run method is executed the following output is printed:
```
{} class=camundajar.impl.scala.collection.convert.JavaCollectionWrappers$MapWrapper
list=null num=null
```

**Expected behavior**
~In the body of the custom_pojo function I would expect to receive the original Java object or at least some kind of Map-proxy with non-empty keys and values.~

The context that is passed to the custom function contains entries for all public fields and for all **public getters**.

**Environment**
Standalone Java app with the Camunda DMN engine:
```
        <dependency>
            <groupId>org.camunda.bpm.dmn</groupId>
            <artifactId>camunda-engine-dmn-bom</artifactId>
            <version>7.16.0</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
```

**Comment by saig0** [comment] 2021-12-01 09:27
@ddavidyuk thank you for reporting :+1: 

It is not expected that the custom function gets the Java POJO because the value is transformed by the FEEL engine into a [FEEL data type](https://camunda.github.io/feel-scala/docs/reference/language-guide/feel-data-types).
I would expect that the value is transformed into a FEEL context. 

I'll verify the behavior :mag:

**Comment by saig0** [comment] 2021-12-01 10:26
I can confirm the behavior with the given test case :heavy_check_mark: 

The POJO is transformed into a FEEL context and then into a `Map` when it is passed to the custom Java function (in the platform integration module). By default, a POJO is evaluated lazily into a context to save resources.

When the context is transformed into a `Map` then all **public** fields of the POJO are put into the map.

So, the example can be fixed by changing the visibility of the fields in the POJO to public. 

@ddavidyuk is this solution sufficient for you?

**Comment by ddavidyuk** [comment] 2021-12-01 10:41
Hi @saig0 ! My expectation was to for the map to contain the values from the public getters as well because I can use them from DMN expressions (e.g. input = pojo_input.list or pojo_input.num will work with private list and num fields and public getters).

**Comment by saig0** [comment] 2021-12-06 05:49
@ddavidyuk thank you for your input :+1:

I'm fine with exposing the public getters to the context. 
I'll treat it as a feature request because it changes the behavior to fulfill a new requirement.

**Closed** 2022-05-12 09:21 UTC
Labels: type: enhancement, scope: camunda-bpm
