### ISSUE TITLE
list function max not handling null values

### ISSUE THREAD

**Issue by hawksdoves** [camunda/feel-scala#382] opened 2021-12-31 10:19 UTC
**Describe the bug**
When using the list function max, if one of the values is a ValNull the function will return a null value as it is deemed as not comparable (I assume this could also be a bug for other list functions as well)

**To Reproduce**
max(null, 0.005, 0.005)

has error of:
_org.camunda.feel.FeelEngine - ValList(List(ValNull, ValNumber(0.5), ValNumber(0.5))) is not comparable_
and it returns: _ValNull_

**Expected behavior**
examples
max(null, 0.005, 0.005) = 0.005
max(null, 0.002, 0.005) = 0.005

**Comment by hawksdoves** [comment] 2021-12-31 10:54
I believe it just needs to be updated [here](https://github.com/camunda/feel-scala/blob/068d4e8e5fb5e25ff18739b0bb7b7183a3137d3c/src/main/scala/org/camunda/feel/syntaxtree/Val.scala#L94) Happy to raise a pr such that it can handle nulls (by just ignoring them)

**Comment by saig0** [comment] 2022-01-03 08:38
I see your point and agree that it would be handy. But according to the DMN spec, I don’t think that this expectation is correct. The function `min()`/`max()` expects a non-empty list of comparable items. But `null` is not comparable.

![image](https://user-images.githubusercontent.com/4305769/147911682-63eb0f6c-cb26-4208-8c37-8338385a9c55.png)

Since the function is defined by the DMN spec, I would like to stay with the spec and don't change the behavior. 

@hawksdoves does this make sense for you?

---

Related forum discussion: https://forum.camunda.org/t/feelengine-not-handling-null-values-for-list-functions/32201

**Comment by hawksdoves** [comment] 2022-01-03 11:00
If the list is a list of Options<t>, then the default scala behaviour of max and min does behave as I have stated ie it ignores None and compares only the Some. I would expect this behaviour here.

**Comment by hawksdoves** [comment] 2022-01-03 11:14
The user case is a complex drd, with multiple tables and a final expression, where a table outputs new inputs that are passed to the next table. Depending on what rule is matched, maybe one of the new inputs are null.
If the expression is max(new_input1, input2, new_input2, input6), then there is a chance that new_input1 and/or new_input2 are null values (as they are dependent on what rules were matched in the previous tables). 
The current behaviour defaults this expression to null, which is clearly not the desired or appropriate response.

**Comment by saig0** [comment] 2022-01-03 12:54
@hawksdoves yes, I see that the filter of `null` values would be useful :+1: 

However, as far as I can see, this is currently not covered by the DMN spec in this way. I suggest reporting an issue in the DMN spec here: https://issues.omg.org/issues/create-new-issue?specification=DMN%231.3

If the issue is accepted then I'm happy to change the behavior. But before, I would like to stay with the defined behavior.

As a workaround, you could filter `null` values. For example,

```
max([new_input1, input2, new_input2, input6][item != null])
```

@hawksdoves is this okay for you?

**Comment by saig0** [comment] 2023-06-01 08:37
There is no new input for more than a year. So, I refer to the [workaround](https://github.com/camunda/feel-scala/issues/382#issuecomment-1004071584) and close the issue. 

Feel free to re-open the issue if there is any new input on this topic.

**Closed by saig0** 2023-06-01 08:37 UTC
Labels: type: bug
