### ISSUE TITLE
Fails to parse long string literals

### ISSUE THREAD

**Issue by adamzr** [camunda/feel-scala#305] opened 2021-07-27 18:27 UTC
**Describe the bug**
Expression parser fails on long string literals

**To Reproduce**
```
    for (int i = 0; i < 1_000_000; i += 10) {
      final String randomChars = RandomStringUtils.randomAlphabetic(i);
      System.out.println(i);
      engine.parseExpression("\"" + randomChars + "\""); // fails at 2,780 chars
    }
```

**Expected behavior**
Expression parses as a long string literal

**Actual behavior**
```
java.lang.StackOverflowError
	at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:4886)
	at java.base/java.util.regex.Pattern$BranchConn.match(Pattern.java:4763)
	at java.base/java.util.regex.Pattern$CharProperty.match(Pattern.java:3996)
```
(goes on forever)

**Environment**
* FEEL engine version: 1.12.4
* Affects: 
  * Camunda BPM: _Unknown_
  * Zeebe broker: 0.26.5

**Comment by adamzr** [comment] 2021-07-27 18:30
In my code example I was using org.apache.commons.lang3.RandomStringUtils. It fails at different points each time the test is run.

**Comment by saig0** [comment] 2021-07-28 03:27
@adamzr thank you for reporting. 

Why do you need such a long string literal?
What is the expected size for your use case?

**Comment by adamzr** [comment] 2021-07-28 18:38
@saig0 The user can control the input of the step. So, we use an input mapping. In this case we don't want the string to be parsed as a FEEL expression, so we escape the text into base64 and wrap it in quotes. That way the user can't use FEEL. Because it's user input and it's base64 encoded it can get quite long. I don't have a max size.

The failure handling from FEEL and Zeebe here is very bad. As soon as we send the workflow YAML with the bad FEEL expression into Zeebe, Zeebe fails on the FEEL parse, then declares the partition to be bad. We found no way to recover Zeebe.

It's very concerning to me that:
a) A bad FEEL expression can crash the parser
b) A bad FEEL expression in a Zeebe workflow can crash Zeebe and make it unrecoverable

**Comment by saig0** [comment] 2021-08-05 07:40
I can confirm the issue in FEEL-Scala version `1.12.4`.
 
Luckily, the issue is fixed in FEEL-Scala version `1.13.2` :sparkles:  
I recommend updating your Zeebe cluster to version >= `1.0.0` (or better starting with a fresh cluster of the new version).

You should also think about other ways to model your process. Instead of generating a new process with the custom encoded string, you could use a process variable that is passed in on creation.

**Closed** 2021-08-05 07:40 UTC
Labels: scope: zeebe, type: bug

**Comment by adamzr** [comment] 2021-08-06 17:48
@saig0 We cannot upgrade easily to Zeebe 1.0.0 or better because we use YAML workflows and I believe that 1.0.0 drops support for them. Can we get Zeebe pre-1.0.0 patched to use the newer version of FEEL?

**Comment by saig0** [comment] 2021-08-06 20:30
Unfortunately, not. Zeebe versions < 1.0.0 running out of support. 

I recommend to upgrade Zeebe. You can generate workflows using the Java BPMN model API. It is more powerful than the YAML workflows.
